### ISSUE TITLE
Internal domain appearing instead of registry.centos.org

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-pipeline-service#516] opened 2018-03-10 01:35 UTC
Our *.rdu2.centos.org domain  keeps appearing on the registry UI, we'll need to investigate and fix this.

**Comment by bamachrn** [comment] 2018-03-14 04:50
same as https://github.com/CentOS/container-pipeline-service/issues/508

**Comment by navidshaikh** [comment] 2018-04-02 14:14
Duplicate of #508

**Closed by navidshaikh** 2018-04-02 14:14 UTC
